/* Shared search and filters. No network requests; the original assortment is retained. */
(function(root){
 'use strict';
 const aliases={айфон:'iphone',айфоны:'iphone',айфона:'iphone',макбук:'macbook',макбуки:'macbook',мак:'mac',айпад:'ipad',айпады:'ipad',аирподс:'airpods',эйрподс:'airpods',эирподс:'airpods',эпл:'apple',вотч:'watch',часы:'watch',наушники:'airpods',ноутбук:'macbook',ноутбуки:'macbook',планшет:'ipad',планшеты:'ipad',смартфон:'iphone',телефон:'iphone',телефоны:'iphone',про:'pro',эйр:'air',гб:'gb',тб:'tb',белый:'white',черный:'black',серебристый:'silver',голубой:'blue',фиолетовый:'purple',бордовый:'burgundy'};
 const keys=['memory','color','chip','sim'];
 const blank=()=>({memory:[],color:[],chip:[],sim:[],min:'',max:''});
 function distance(a,b){if(a===b)return 0;const d=Array.from({length:a.length+1},()=>new Array(b.length+1));for(let i=0;i<=a.length;i++)d[i][0]=i;for(let j=0;j<=b.length;j++)d[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++){d[i][j]=Math.min(d[i-1][j]+1,d[i][j-1]+1,d[i-1][j-1]+(a[i-1]===b[j-1]?0:1));if(i>1&&j>1&&a[i-1]===b[j-2]&&a[i-2]===b[j-1])d[i][j]=Math.min(d[i][j],d[i-2][j-2]+1)}return d[a.length][b.length]}
 function fold(s){return String(s||'').toLowerCase().replace(/ё/g,'е').replace(/([0-9])([a-zа-я])/g,'$1 $2').replace(/([a-zа-я])([0-9])/g,'$1 $2').replace(/[^a-zа-я0-9]+/g,' ').trim()}
 function normalize(s){return fold(s).replace(/мак\s+бук/g,'макбук').replace(/mac\s+book/g,'macbook').replace(/ай\s+фон/g,'айфон').replace(/air\s+pods/g,'airpods').split(/\s+/).filter(Boolean).map(word=>{if(aliases[word])return aliases[word];if(word.length>=3&&/[а-я]/.test(word)){const prefix=Object.keys(aliases).find(alias=>alias.startsWith(word));if(prefix)return aliases[prefix]}if(!/[а-я]/.test(word)||word.length<4)return word;let closest=word,best=word.length>=6?3:2;for(const [alias,value]of Object.entries(aliases)){if(Math.abs(alias.length-word.length)>2)continue;const diff=distance(alias,word);if(diff<best){closest=value;best=diff}}return closest}).join(' ')}
 const keyboard={q:'й',w:'ц',e:'у',r:'к',t:'е',y:'н',u:'г',i:'ш',o:'щ',p:'з','[':'х',']':'ъ',a:'ф',s:'ы',d:'в',f:'а',g:'п',h:'р',j:'о',k:'л',l:'д',';':'ж',"'":'э',z:'я',x:'ч',c:'с',v:'м',b:'и',n:'т',m:'ь',',':'б','.':'ю'};
 function decodeKeyboard(s){return String(s).toLowerCase().split('').map(c=>keyboard[c]||c).join('')}
 function attributes(p){const spec=p.specs||{},connection=spec['SIM (версия США)']||spec['Связь']||'';return {memory:p.memory?.length?p.memory:spec['Встроенная память']?[spec['Встроенная память']]:[],color:p.colors||[],chip:[spec['Процессор']||spec['Чип']].filter(Boolean),sim:connection?/dual\s*esim/i.test(connection)?['Dual eSIM']:[connection]:[]}}
 // Compatibility mentions must not make a watch appear in an iPhone search.
 const searchIndex=new WeakMap();
 function haystack(p){if(searchIndex.has(p))return searchIndex.get(p);const a=attributes(p),specs=Object.entries(p.specs||{}).filter(([key])=>!/^Совместимость$/i.test(key)).map(([,value])=>value),tokens=normalize([p.name,p.category,...Object.values(a).flat(),...(p.highlights||[]),...specs].join(' ')).split(' ');searchIndex.set(p,tokens);return tokens}
 function wordCost(word,tokens){let best=Infinity;for(const token of tokens){if(word===token)return 0;if(/^\d+$/.test(word)||/^\d+$/.test(token))continue;if(word.length>=2&&token.startsWith(word))best=Math.min(best,.2);else if(word.length>=4&&token.includes(word))best=Math.min(best,.4);if(word.length>=4&&Math.abs(word.length-token.length)<=2){const diff=distance(word,token),limit=word.length>=6?2:1;if(diff<=limit)best=Math.min(best,1+diff)}}return best}
 function search(list,query=''){const raw=String(query).trim().slice(0,160);if(!raw)return list.slice();const variants=[normalize(raw),normalize(decodeKeyboard(raw))].filter(Boolean).map(q=>q.split(' '));return list.map((p,index)=>{const tokens=haystack(p);return {p,index,score:Math.min(...variants.map(words=>words.reduce((sum,w)=>sum+wordCost(w,tokens),0)))}}).filter(x=>Number.isFinite(x.score)).sort((a,b)=>a.score-b.score||a.index-b.index).map(x=>x.p)}
 function matches(p,f=blank()){const a=attributes(p);return keys.every(k=>!f[k]?.length||f[k].some(value=>a[k].includes(value)))&&(!f.min||p.price>=Number(f.min))&&(!f.max||p.price<=Number(f.max))}
 function options(list,category='Все'){const relevant=list.filter(p=>category==='Все'||p.category===category);return Object.fromEntries(keys.map(key=>[key,[...new Set(relevant.flatMap(p=>attributes(p)[key]))]]))}
 function sanitize(f,list,category='Все'){const available=options(list,category),result=blank();for(const k of keys)result[k]=[...new Set((Array.isArray(f[k])?f[k]:[]).filter(v=>available[k].includes(v)))];for(const k of ['min','max']){const n=Number(f[k]);result[k]=String(f[k]??'').trim()&&Number.isFinite(n)&&n>=0?String(n):''}return result}
 function fromParams(params){const f=blank();for(const key of keys)f[key]=params.getAll(key);for(const key of ['min','max']){const val=params.get(key);if(val!==null&&val!==''&&Number.isFinite(Number(val))&&Number(val)>=0)f[key]=String(Number(val))}return f}
 function writeParams(params,f){for(const key of keys){params.delete(key);for(const val of f[key]||[])params.append(key,val)}for(const key of ['min','max'])f[key]?params.set(key,f[key]):params.delete(key)}
 function validRange(f){return !f.min||!f.max||Number(f.min)<=Number(f.max)}
 function count(f){return keys.reduce((n,k)=>n+(f[k]?.length||0),0)+(f.min||f.max?1:0)}
 root.IShopCatalog={keys,blank,distance,normalize,search,matches,attributes,options,sanitize,fromParams,writeParams,validRange,count};
})(globalThis);
